version = 1



[[annotations]]
path = [
    "CHANGELOG.md",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2017 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>"
SPDX-License-Identifier = "Apache-2.0"


[[annotations]]
path = [
    ".releaserc",
    "firebase.json",
    "package-lock.json",
    "package.json",
    "content/content.config.sample.json",
    "content/service-status.sample.json",
    "src/Languages/appTranslationTablesViews/all-views/en.json",
    "src/Languages/appTranslationTablesViews/all-views/fr.json",
    "src/Languages/appTranslationTablesViews/login/en.json",
    "src/Languages/appTranslationTablesViews/login/fr.json",
    "src/Languages/appTranslationTablesViews/top-view/en.json",
    "src/Languages/appTranslationTablesViews/top-view/fr.json",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2020 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>"
SPDX-License-Identifier = "Apache-2.0"


[[annotations]]
path = [
    ".gitlab/merge_request_templates/Default.md",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2021 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>"
SPDX-License-Identifier = "Apache-2.0"


[[annotations]]
path = [
    "res/**",
    "static/landingpage/Opal_Name_Logo_Transparent.png",
    "static/landingpage/opal-tiny.ico",
    "src/img/apple-touch-icon.png",
    "src/img/Opal_Logo_Black.png",
    "src/img/Opal_Logo_Transparent_Inverse_Icon.png",
    "src/img/Opal_Logo_Transparent_Inverse.png",
    "src/img/Opal_Name_Logo_Green_Transparent.png",
    "src/img/Opal_Name_Logo_Transparent.png",
    "src/img/Opal_Name_Logo.png",
    "src/img/opal_notification.png",
    "src/img/OpalHealth_App_Apple_Icon_2.png",
    "src/img/web-icon-512.png",
    "src/img/web-icon-192.png",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2015 Ackeem Joseph <ackeem.joseph@muhc.mcgill.ca>"
SPDX-License-Identifier = "LicenseRef-OpalTrademarks"


[[annotations]]
path = [
    "static/landingpage/neuro-and-montreal.png",
]
precedence = "override"
# See:
#    - https://commons.wikimedia.org/wiki/File:The_Montreal_Neurological_Institute_and_Hospital_%28The_Neuro%29.jpg
#    - https://commons.wikimedia.org/wiki/File:Montreal-canada-parc-urban.jpg
SPDX-FileCopyrightText = [
    "Copyright (C) 2018 Neuro1234",
    "Copyright (C) 2025 Opal Health Informatics Group at the Research Institute of the McGill University Health Centre <john.kildea@mcgill.ca>",
]
SPDX-License-Identifier = "CC-BY-SA-4.0"
SPDX-FileComment = "The original image of Neurological Institute was cropped and merged with an image of Montreal."


[[annotations]]
path = [
    "src/img/fleur-de-lys-quebec.svg",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 1948 Gouvernement du Qu√©bec"
SPDX-License-Identifier = "LicenseRef-FleurDeLysDuQuebec"


[[annotations]]
path = [
    "src/img/opal-init-photo.jpg",
]
precedence = "override"
# See:
#   - https://www.deviantart.com/duckfarm/art/Yellow-Green-311796216
#   - https://alphacoders.com/author/view/16321
SPDX-FileCopyrightText = "Copyright (C) 2012 Adam Valstar"
SPDX-License-Identifier = "CC-BY-NC-ND-3.0"


[[annotations]]
path = [
    "src/fonts/Roboto-Regular.ttf",
]
precedence = "override"
SPDX-FileCopyrightText = "Copyright (C) 2011 The Roboto Project Authors (https://github.com/googlefonts/roboto-classic)"
SPDX-License-Identifier = "OFL-1.1"
